from building import *

cwd     = GetCurrentDir()
src     = []
CPPPATH = [cwd]

src     += Split("""
    wifi_port.c
    package/rfparam/Src/rfparam_adapter.c
    package/rfparam/Src/rfparam_rftlv.c
    package/wireless/wifi6/bl6_os_adapter/src/rtos_al.c
    package/wireless/wifi6/bl6_os_adapter/src/platform_bouffalo_sdk.c
    package/getopt/utils_getopt.c
""")
CPPPATH += [cwd + r'/package/rfparam/Inc']
CPPPATH += [cwd + r'/package/rf/inc']
CPPPATH += [cwd + r'/package/wireless/wifi6/inc',
            cwd + r'/package/wireless/wifi6/bl6_os_adapter/include']
CPPPATH += [cwd + r'/package/getopt']

libs = ['libwifi6', 'librf']
libpath = [cwd + r'/package/wireless/wifi6/lib',
           cwd + r'/package/rf/lib']


src += Split("""
    package/lwip/lwip/src/api/api_lib.c
    package/lwip/lwip/src/api/api_msg.c
    package/lwip/lwip/src/api/err.c
    package/lwip/lwip/src/api/if_api.c
    package/lwip/lwip/src/api/netbuf.c
    package/lwip/lwip/src/api/netdb.c
    package/lwip/lwip/src/api/netifapi.c
    package/lwip/lwip/src/api/sockets.c
    package/lwip/lwip/src/api/tcpip.c
    package/lwip/lwip/src/api/api_lib.c
    package/lwip/lwip/src/core/altcp_alloc.c
    package/lwip/lwip/src/core/altcp_tcp.c
    package/lwip/lwip/src/core/altcp.c
    package/lwip/lwip/src/core/def.c
    package/lwip/lwip/src/core/dns.c
    package/lwip/lwip/src/core/inet_chksum.c
    package/lwip/lwip/src/core/init.c
    package/lwip/lwip/src/core/ip.c
    package/lwip/lwip/src/core/mem.c
    package/lwip/lwip/src/core/memp.c
    package/lwip/lwip/src/core/netif.c
    package/lwip/lwip/src/core/pbuf.c
    package/lwip/lwip/src/core/raw.c
    package/lwip/lwip/src/core/stats.c
    package/lwip/lwip/src/core/sys.c
    package/lwip/lwip/src/core/tcp_in.c
    package/lwip/lwip/src/core/tcp_out.c
    package/lwip/lwip/src/core/tcp.c
    package/lwip/lwip/src/core/timeouts.c
    package/lwip/lwip/src/core/tcp.c
    package/lwip/lwip/src/core/timeouts.c
    package/lwip/lwip/src/core/udp.c
    package/lwip/lwip/src/core/ipv4/autoip.c
    package/lwip/lwip/src/core/ipv4/dhcp.c
    package/lwip/lwip/src/core/ipv4/etharp.c
    package/lwip/lwip/src/core/ipv4/icmp.c
    package/lwip/lwip/src/core/ipv4/igmp.c
    package/lwip/lwip/src/core/ipv4/ip4_addr.c
    package/lwip/lwip/src/core/ipv4/ip4_frag.c
    package/lwip/lwip/src/core/ipv4/ip4.c
    package/lwip/lwip/src/core/ipv6/dhcp6.c
    package/lwip/lwip/src/core/ipv6/ethip6.c
    package/lwip/lwip/src/core/ipv6/icmp6.c
    package/lwip/lwip/src/core/ipv6/inet6.c
    package/lwip/lwip/src/core/ipv6/ip6_addr.c
    package/lwip/lwip/src/core/ipv6/ip6_frag.c
    package/lwip/lwip/src/core/ipv6/ip6.c
    package/lwip/lwip/src/core/ipv6/mld6.c
    package/lwip/lwip/src/core/ipv6/nd6.c
    package/lwip/lwip/system/os/sys_arch.c
    package/lwip/lwip/src/netif/ethernet.c
""")
             

CPPPATH += [cwd + r'/package/lwip/lwip/src/include',
            cwd + r'/package/lwip/lwip',
            cwd + r'/package/lwip/lwip/system']

src += Split("""
    package/lwip/lwip_apps/dhcpd/dhcp_server_raw.c
""")
             
CPPPATH += [cwd + r'/package/lwip/lwip_apps/dhcpd']


# mbedtls
    # 
    # package/mbedtls/mbedtls/library/blowfish.c
    # package/mbedtls/mbedtls/library/net_sockets.c
    # package/mbedtls/mbedtls/library/pkparse.c

src += Split("""
    package/mbedtls/mbedtls/library/aes.c
    package/mbedtls/mbedtls/library/aesni.c
    package/mbedtls/mbedtls/library/arc4.c
    package/mbedtls/mbedtls/library/aria.c
    package/mbedtls/mbedtls/library/asn1parse.c
    package/mbedtls/mbedtls/library/asn1write.c
    package/mbedtls/mbedtls/library/base64.c

    package/mbedtls/mbedtls/library/camellia.c
    package/mbedtls/mbedtls/library/ccm.c
    package/mbedtls/mbedtls/library/certs.c
    package/mbedtls/mbedtls/library/chacha20.c
    package/mbedtls/mbedtls/library/chachapoly.c
    package/mbedtls/mbedtls/library/cipher_wrap.c
    package/mbedtls/mbedtls/library/cipher.c
    package/mbedtls/mbedtls/library/cmac.c
    package/mbedtls/mbedtls/library/ctr_drbg.c
    package/mbedtls/mbedtls/library/constant_time.c
    package/mbedtls/mbedtls/library/debug.c
    package/mbedtls/mbedtls/library/dhm.c
    package/mbedtls/mbedtls/library/ecdh.c
    package/mbedtls/mbedtls/library/ecjpake.c
    package/mbedtls/mbedtls/library/ecp_curves.c
    package/mbedtls/mbedtls/library/ecp.c
    package/mbedtls/mbedtls/library/entropy.c
    package/mbedtls/mbedtls/library/error.c
    package/mbedtls/mbedtls/library/gcm.c
    package/mbedtls/mbedtls/library/havege.c
    package/mbedtls/mbedtls/library/hkdf.c
    package/mbedtls/mbedtls/library/hmac_drbg.c
    package/mbedtls/mbedtls/library/md.c
    package/mbedtls/mbedtls/library/md2.c
    package/mbedtls/mbedtls/library/md4.c
    package/mbedtls/mbedtls/library/md5.c
    package/mbedtls/mbedtls/library/memory_buffer_alloc.c

    package/mbedtls/mbedtls/library/nist_kw.c
    package/mbedtls/mbedtls/library/oid.c
    package/mbedtls/mbedtls/library/padlock.c
    package/mbedtls/mbedtls/library/pem.c
    package/mbedtls/mbedtls/library/pk_wrap.c
    package/mbedtls/mbedtls/library/pk.c
    package/mbedtls/mbedtls/library/pkcs5.c
    package/mbedtls/mbedtls/library/pkcs11.c
    package/mbedtls/mbedtls/library/pkcs12.c
    
    package/mbedtls/mbedtls/library/pkwrite.c
    package/mbedtls/mbedtls/library/platform_util.c
    package/mbedtls/mbedtls/library/platform.c
    package/mbedtls/mbedtls/library/poly1305.c
    package/mbedtls/mbedtls/library/psa_crypto_aead.c
    package/mbedtls/mbedtls/library/psa_crypto_cipher.c
    package/mbedtls/mbedtls/library/psa_crypto_client.c
    package/mbedtls/mbedtls/library/psa_crypto_driver_wrappers.c
    package/mbedtls/mbedtls/library/psa_crypto_ecp.c
    package/mbedtls/mbedtls/library/psa_crypto_hash.c
    package/mbedtls/mbedtls/library/psa_crypto_mac.c
    package/mbedtls/mbedtls/library/psa_crypto_rsa.c
    package/mbedtls/mbedtls/library/psa_crypto_se.c
    package/mbedtls/mbedtls/library/psa_crypto_slot_management.c
    package/mbedtls/mbedtls/library/psa_crypto_storage.c
    package/mbedtls/mbedtls/library/psa_crypto.c
    package/mbedtls/mbedtls/library/psa_its_file.c
    package/mbedtls/mbedtls/library/ripemd160.c
    package/mbedtls/mbedtls/library/rsa_internal.c
    package/mbedtls/mbedtls/library/rsa.c
    package/mbedtls/mbedtls/library/sha1.c
    package/mbedtls/mbedtls/library/sha256.c
    package/mbedtls/mbedtls/library/sha512.c
    package/mbedtls/mbedtls/library/ssl_cache.c
    package/mbedtls/mbedtls/library/ssl_ciphersuites.c
    package/mbedtls/mbedtls/library/ssl_cli.c
    package/mbedtls/mbedtls/library/ssl_cookie.c
    package/mbedtls/mbedtls/library/ssl_msg.c
    package/mbedtls/mbedtls/library/ssl_srv.c
    package/mbedtls/mbedtls/library/ssl_ticket.c
    package/mbedtls/mbedtls/library/ssl_tls.c
    package/mbedtls/mbedtls/library/ssl_tls13_keys.c
    package/mbedtls/mbedtls/library/threading.c
    package/mbedtls/mbedtls/library/timing.c
    package/mbedtls/mbedtls/library/version_features.c
    package/mbedtls/mbedtls/library/version.c
    package/mbedtls/mbedtls/library/x509_create.c
    package/mbedtls/mbedtls/library/x509_crl.c
    package/mbedtls/mbedtls/library/x509_crt.c
    package/mbedtls/mbedtls/library/x509_csr.c
    package/mbedtls/mbedtls/library/x509.c
    package/mbedtls/mbedtls/library/x509write_crt.c
    package/mbedtls/mbedtls/library/x509write_csr.c


    package/mbedtls/port/platform/mbedtls_port_bouffalo_sdk.c
    package/mbedtls/port/pkparse.c
    package/mbedtls/port/bignum_ext.c
    package/mbedtls/port/hw_entropy_poll.c
    package/mbedtls/port/net_sockets.c  
""")
    #      package/mbedtls/port/hw_entropy_poll.c

# HW
src += ['package/mbedtls/mbedtls/library/bignum.c']

CPPPATH += [cwd + r'/package/mbedtls/mbedtls/library',
            cwd + r'/package/mbedtls/mbedtls/include',
            cwd + r'/package/mbedtls/port/platform']

LOCAL_CFLAGS = ' -DBOUFFALO_SDK -DRFPARAM_BL616'
LOCAL_CFLAGS += ' -DMBEDTLS_NET_C'
LOCAL_CFLAGS += ' -DMBEDTLS_CONFIG_FILE="<mbedtls_sample_config.h>"'

group = DefineGroup('wifi', src, depend = [''], CPPPATH = CPPPATH, LIBS = libs, LIBPATH = libpath, LOCAL_CFLAGS = LOCAL_CFLAGS)

Return('group')
