from building import *

cwd     = GetCurrentDir()
src     = []
CPPPATH = [cwd]

src     += Split("""
    wifi_port.c
    package/rfparam/Src/rfparam_adapter.c
""")
CPPPATH += [cwd + r'/package/rfparam/Inc']
CPPPATH += [cwd + r'/package/rf/inc']
CPPPATH += [cwd + r'/package/wireless/wifi6/inc',
            cwd + r'/package/wireless/wifi6/bl6_os_adapter/include']

libs = ['libwifi6', 'librf']
libpath = [cwd + r'/package/wireless/wifi6/lib',
           cwd + r'/package/rf/lib']

group = DefineGroup('wifi', src, depend = [''], CPPPATH = CPPPATH, LIBS = libs, LIBPATH = libpath)

Return('group')
